[project]
name = "hyurl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dm-tree>=0.1.9",
    "gymnasium[atari]>=1.2.3",
    "rich>=14.3.3",
    "tensorboard>=2.20.0",
    "torch>=2.11.0",
]

[tool.uv]
index-url = "https://pypi.tuna.tsinghua.edu.cn/simple"

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true
