# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import predictor_pb2 as proto_dot_predictor__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/predictor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class PredictorServiceStub(object):
    """定义一个服务和两个接口
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Inference = channel.unary_unary(
                '/PredictorService/Inference',
                request_serializer=proto_dot_predictor__pb2.InferenceReq.SerializeToString,
                response_deserializer=proto_dot_predictor__pb2.InferenceRsp.FromString,
                _registered_method=True)
        self.LogProbs = channel.unary_unary(
                '/PredictorService/LogProbs',
                request_serializer=proto_dot_predictor__pb2.InferenceReq.SerializeToString,
                response_deserializer=proto_dot_predictor__pb2.InferenceRsp.FromString,
                _registered_method=True)
        self.UpdateWeight = channel.unary_unary(
                '/PredictorService/UpdateWeight',
                request_serializer=proto_dot_predictor__pb2.UpdateWeightReq.SerializeToString,
                response_deserializer=proto_dot_predictor__pb2.UpdateWeightRsp.FromString,
                _registered_method=True)


class PredictorServiceServicer(object):
    """定义一个服务和两个接口
    """

    def Inference(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LogProbs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateWeight(self, request, context):
        """rpc AsyncInference(InferenceReq) returns (InferenceRsp);
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PredictorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Inference': grpc.unary_unary_rpc_method_handler(
                    servicer.Inference,
                    request_deserializer=proto_dot_predictor__pb2.InferenceReq.FromString,
                    response_serializer=proto_dot_predictor__pb2.InferenceRsp.SerializeToString,
            ),
            'LogProbs': grpc.unary_unary_rpc_method_handler(
                    servicer.LogProbs,
                    request_deserializer=proto_dot_predictor__pb2.InferenceReq.FromString,
                    response_serializer=proto_dot_predictor__pb2.InferenceRsp.SerializeToString,
            ),
            'UpdateWeight': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateWeight,
                    request_deserializer=proto_dot_predictor__pb2.UpdateWeightReq.FromString,
                    response_serializer=proto_dot_predictor__pb2.UpdateWeightRsp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PredictorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('PredictorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PredictorService(object):
    """定义一个服务和两个接口
    """

    @staticmethod
    def Inference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PredictorService/Inference',
            proto_dot_predictor__pb2.InferenceReq.SerializeToString,
            proto_dot_predictor__pb2.InferenceRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LogProbs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PredictorService/LogProbs',
            proto_dot_predictor__pb2.InferenceReq.SerializeToString,
            proto_dot_predictor__pb2.InferenceRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateWeight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PredictorService/UpdateWeight',
            proto_dot_predictor__pb2.UpdateWeightReq.SerializeToString,
            proto_dot_predictor__pb2.UpdateWeightRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
